tabWidth: 4
singleQuote: true
semi: true
trailingComma: 'none'
printWidth: 100
bracketSameLine: true

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      tabWidth: 2
      useTabs: false
