# fly.toml app configuration file generated for remembit-stg on 2025-01-12T19:59:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remembit-stg'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'remembit_pb_data'
  destination = '/remembit/pb_data'
  initial_size = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
