name: local-dev

services:
  remembit:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: pocketbase
    expose:
      - '8080'
    ports:
      - '127.0.0.1:8080:8080'
    command: ['serve', '--dev', '--http=0.0.0.0:8080']
    volumes:
      - type: bind
        source: ../backend/pocketbase/pb_migrations
        target: /pb/pb_migrations
