name: Deploy Production

on:
  push:
    tags: ['v[0-9].[0-9].[0-9]']

jobs:
  build:
    uses: ./.github/workflows/callable-build.yml
    with:
      output-artifacts: true # this tells workflow to output an artifact calld "web"
      environment: prod
    secrets:
      REMEMBIT_SUPABASE_URL: ${{ secrets.REMEMBIT_SUPABASE_URL }}
      REMEMBIT_SUPABASE_ANON_KEY: ${{ secrets.REMEMBIT_SUPABASE_ANON_KEY }}

  supabase:
    needs: [build]
    uses: ./.github/workflows/callable-deploy-supabase.yml
    with:
      environment: prod
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}

  web:
    needs: [build, supabase]
    uses: ./.github/workflows/callable-deploy-web.yml # this expects an artifact named "web"
    with:
      environment: prod
      url: https://remembit.app
    secrets:
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
