name: Deploy Staging

on:
  push:
    branches: [main]
    tags-ignore: ['v[0-9].[0-9].[0-9]']
    paths-ignore: ['.github/workflows/**']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/callable-build.yml
    with:
      output-artifacts: true # this tells workflow to output an artifact calld "web"
      environment: Staging
    secrets: inherit

  supabase:
    needs: [build]
    uses: ./.github/workflows/callable-deploy-supabase.yml
    with:
      environment: Staging
    secrets: inherit

  web:
    needs: [build, supabase]
    uses: ./.github/workflows/callable-deploy-web.yml # this expects an artifact named "web"
    with:
      environment: Staging
      url: https://stg.remembit.app
    secrets: inherit
