name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  staging:
    name: Staging
    needs: [ci]
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      environment: Staging
      environment_url: https://stg.remembit.app
      git-ref: ${{ github.github.ref }}
    secrets: inherit
