name: pr

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

env:
  DOCKERHUB_REPOSITORY: ungnome/remembit

jobs:
  pr-title-linter:
    name: lint pr title
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5

  build:
    name: build
    runs-on: ubuntu-latest
    environment: pull-request
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: configure .env
        shell: bash
        run: |
          echo "configuring .env"
          echo "PUBLIC_POCKETBASE_URL=${{ vars.PUBLIC_POCKETBASE_URL }}" > .env

      - name: build web
        working-directory: web
        shell: bash
        run: |
          pnpm install
          pnpm run build

      - name: image metadata
        id: image-metadata
        uses: docker/metadata-action@v5
        with:
          images: ungnome/remembit

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: build and publish image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}
