name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.annotate-release.outputs.release-tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Cut Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate Release
        id: annotate-release
        run: |
          $RELEASE_TAG=v$(cat package.json | jq -r .version)
          echo "::notice title=Version::$RELEASE_TAG"
          echo "::set-output name=release-tag::$RELEASE_TAG"
