name: reusable_deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      environment_url:
        type: string
        required: true
      git-ref:
        type: string
        required: true

jobs:
  supabase:
    name: supbabase
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - name: install supabase cli
        uses: supabase/setup-cli@v1
        with:
          version: 1.1.6

      - name: supabase link
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: push db changes
        run: supabase db push --debug

  frontend:
    name: frontend
    runs-on: ubuntu-latest
    needs: [supabase]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: deploy
        run: curl -X POST "${{secrets.RENDER_DEPLOY_WEBHOOK}}&ref=${{ inputs.git-ref }}"
