name: staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: staging
    environment:
      name: staging
      url: https://stg.remembit.app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: signin to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # this should push an image with branch name as the tag
      - name: build
        uses: ./.github/actions/build
        with:
          image-registry: ghcr.io
          image-name: ungnome/remembit
          image-push: true
          vite-mode: staging

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: fly deploy
        run: flyctl deploy --config fly-staging.toml --image ghcr.io/ungnome/remembit:${{ github.ref_name }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
